version: "3.9"
services:
  app:
    build: .
    container_name: e_commerce_project
    ports:
      - "8087:8087"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/e_commerce
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: e_commerce_psql
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: e_commerce
    ports:
      - "5434:5432"
    volumes:
      - e_commerce_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "2000:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  e_commerce_data:
  pgadmin-data:
